from typing import Any, List, Optional, Union, TypeVar, Sequence

T = TypeVar('T')

class Model:
    def __init__(self) -> None: ...
    def solve(self) -> bool: ...

class Expression:
    def value(self) -> Any: ...
    def __str__(self) -> str: ...

class IntVar(Expression):
    def __init__(self, lb: int, ub: int, name: Optional[str] = None) -> None: ...
    def value(self) -> int: ... 